src/Pawelby/Models/Trip.cs
#region Usings
    using System;
    using System.Collections.Generic;
#endregion

namespace Pawelby.Models
{
    /// <summary>
    /// Trip model
    /// </summary>
    public class Trip
    {
#region Properties
        /// <summary>
        /// Id of the trip
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Name of the trip
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Created date of the trip
        /// </summary>
        public DateTime Created { get; set; }
        /// <summary>
        /// Username of the trip
        /// </summary>
        public string UserName { get; set; }

        /// <summary>
        /// Stops collection of the trip
        /// </summary>
        public ICollection<Stop> Stops { get; set; }
#endregion
    }
}

src/Pawelby/ViewModels/TripViewModel.cs
#region Usings
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
#endregion

namespace Pawelby.ViewModels
{
    /// <summary>
    /// Trip view model
    /// </summary>
    public class TripViewModel
    {
#region Properties
        /// <summary>
        /// Id of the trip
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Name of the trip
        /// </summary>
        [Required(ErrorMessage = "Название обязательно")]
        [StringLength(255, MinimumLength = 5)]
        public string Name { get; set; }

        /// <summary>
        /// Created date of the trip
        /// </summary>
        public DateTime Created { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Stops of the trip
        /// </summary>
        public IEnumerable<StopViewModel> Stops { get; set; }
#endregion

    }
}

src/Pawelby/Controllers/Api/TripController.cs
#region Usings
using System;
using System.Collections.Generic;
using System.Net;
using AutoMapper;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Mvc;
using Microsoft.Framework.Logging;
using Pawelby.Models;
using Pawelby.ViewModels;
#endregion

namespace Pawelby.Controllers.Api
{
    /// <summary>
    /// Trip controller
    /// </summary>
    [Authorize]
    [Route("api/trips")]
    public class TripController : Controller
    {
#region Private fields
        private IPawelbyRepository _repository;
        private ILogger<TripController> _logger;

#endregion
        /// <summary>
        /// Constructor of the Trip Controller
        /// </summary>
        /// <param name="repository">Repository</param>
        /// <param name="logger">Logger</param>
        public TripController(IPawelbyRepository repository, ILogger<TripController> logger)
        {
            _logger = logger;
            _repository = repository;
        }

        /// <summary>
        /// Get all trips with stops for current user
        /// </summary>
        /// <returns></returns>
        [HttpGet("")]
        public JsonResult Get()
        {
            var trips = _repository.GetUserTripsWithStops(User.Identity.Name);
            var results = Mapper.Map<IEnumerable<TripViewModel>>(trips);
            return Json(results);
        }

        /// <summary>
        /// Post a new trip via trip view model
        /// </summary>
        /// <param name="vm">Trip view model</param>
        /// <returns></returns>
        [HttpPost("")]
        public JsonResult Post([FromBody]TripViewModel vm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var newTrip = Mapper.Map<Trip>(vm);
                    newTrip.UserName = User.Identity.Name;

                    _logger.LogInformation("Attempting to save a new trip");
                    _repository.AddTrip(newTrip);

                    if (_repository.SaveAll())
                    {
                        Response.StatusCode = (int) HttpStatusCode.Created;
                        return Json(Mapper.Map<TripViewModel>(newTrip));
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogError("Failed to save new trip", ex);
                Response.StatusCode = (int) HttpStatusCode.BadRequest;
                return Json(new {Message = ex.Message});
            }
            

            Response.StatusCode = (int) HttpStatusCode.BadRequest;
            return Json(new { Message = "Failed", ModelState = ModelState});

        }
    }
}

src/Pawelby/Controllers/Web/AppController.cs
#region Usings
    using Microsoft.AspNet.Authorization;
    using Microsoft.AspNet.Mvc;
    using Pawelby.Services;
    using Pawelby.ViewModels;
#endregion

namespace Pawelby.Controllers.Web
{
    /// <summary>
    /// App Controller
    /// </summary>
    public class AppController : Controller
    {

#region Private fields
        private IMailService _mailService;
#endregion

        /// <summary>
        /// Constructor of App Controller
        /// </summary>
        /// <param name="service">Mail service</param>
        public AppController(IMailService service)
        {
            _mailService = service;
        }

        /// <summary>
        /// Index action
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult Trips()
        {
            return View();
        }


        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            if (ModelState.IsValid)
            {
                var email = Startup.Configuration["AppSettings:SiteEmailAddress"];

                if (string.IsNullOrWhiteSpace(email))
                {
                    ModelState.AddModelError("", "Невозможно отправить email, проблемы конфигурации");
                }

                if (_mailService.SendMail(email,
                    email,
                    $"Contact Page from {model.Name} ({model.Email})",
                    model.Message))
                {
                    ModelState.Clear();

                    ViewBag.Message = "Сообщение отправлено. Спасибо";
                }
            }

            return View();
        }
    }
}

src/Pawelby/Views/App/About.cshtml
@{
    ViewBag.Title = "О сайте";
}

<h2>
    О сайте Pawelby
</h2>

src/Pawelby/Views/App/Contact.cshtml
@model Pawelby.ViewModels.ContactViewModel

@{
    ViewBag.Title = "Контакты";
}

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h2>Контакты</h2>

        <form method="post">
            @if (ViewBag.Message != null)
            {
                <div>@ViewBag.Message</div>
            }
            <div asp-validation-summary="ValidationSummary.ModelOnly"></div>
            <div class="form-group">
                <label asp-for="Name">Имя</label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-muted"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email">Email</label>
                <input type="email" asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-muted"></span>
            </div>
            <div class="form-group">
                <label asp-for="Message">Сообщение</label>
                <textarea cols="40" rows="4" asp-for="Message" class="form-control"></textarea>
                <span asp-validation-for="Message" class="text-muted"></span>
            </div>
            <div class="form-group">
                <a asp-controller="App" asp-action="Index" class="btn btn-default">Отмена</a>
                <input type="submit" value="Отправить сообщение" class="btn btn-success"/>
            </div>
        </form>
    </div>
</div>

src/Pawelby/Views/App/Index.cshtml
@model IEnumerable<Pawelby.Models.Trip>

@{
    ViewBag.Title = "Главная";
}

<div class="row">

    <div class="col-md-12">
        <h1>Добро пожаловать на сайт</h1>
        <p>Сайт поможет вам спланировать путешествие</p>
        <a asp-controller="App" asp-action="trips" class="btn btn-lg btn-success">Показать мои путешествия</a>
    </div>

</div>

src/Pawelby/Views/App/Trips.cshtml
@{
    ViewBag.Title = "Путешествия";
}

@section Scripts {
    <script src="~/lib/underscore/underscore-min.js"></script>
    <script src="~/lib/angular/angular.min.js"></script>
    <script src="~/lib/angular-route/angular-route.min.js"></script>
    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="~/lib/gmaps/gmaps.min.js"></script>
    <script src="~/lib/travelmap/travelmap.min.js"></script>
    <environment names="Development">
        <script src="~/js/simpleControls.js"></script>
        <script src="~/js/app-trips.js"></script>
        <script src="~/js/tripsController.js"></script>
        <script src="~/js/tripEditorController.js"></script>
    </environment>
    <environment names="Production, Staging">
        <script src="~/lib/_app/simpleControls.js"></script>
        <script src="~/lib/_app/app-trips.js"></script>
        <script src="~/lib/_app/tripsController.js"></script>
        <script src="~/lib/_app/tripEditorController.js"></script>
    </environment>
}

<div class="row" ng-app="app-trips">
    
    <div ng-view></div>

</div>