src/Pawelby/Controllers/AuthController.cs
#region Usings
    using System.Threading.Tasks;
    using Microsoft.AspNet.Identity;
    using Microsoft.AspNet.Mvc;
    using Pawelby.Models;
    using Pawelby.ViewModels;
#endregion

namespace Pawelby.Controllers
{
    /// <summary>
    /// Authorization Controller
    /// </summary>
    public class AuthController : Controller
    {
#region Private Filds
        private SignInManager<PawelbyUser> _signInManager;
#endregion

        /// <summary>
        /// Constructor of the Auth Controller
        /// </summary>
        /// <param name="signInManager">SignIn Manager</param>
        public AuthController(SignInManager<PawelbyUser> signInManager)
        {
            _signInManager = signInManager;
        }

        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Trips", "App");
            }

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Login(LoginViewModel vm, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var signInResult = await _signInManager.PasswordSignInAsync(vm.Username,
                    vm.Password,
                    true, false);
                if (signInResult.Succeeded)
                {
                    if (string.IsNullOrWhiteSpace(returnUrl))
                    {
                        return RedirectToAction("Trips", "App");
                    }
                    else
                    {
                        return Redirect(returnUrl);
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Username or password incorrect");
                }
            }

            return View();
        }

        public async Task<ActionResult> Logout()
        {
            if (User.Identity.IsAuthenticated)
            {
                await _signInManager.SignOutAsync();
            }

            return RedirectToAction("Index", "App");
        } 
    }
}

src/Pawelby/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Pawelby @ViewBag.Title</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/lib/bootswatch/spacelab/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" />

</head>

<body>
<div id="sidebar">
    @if (User.Identity.IsAuthenticated)
    {
        <img src="~/img/pawelby.jpg" alt="avatar" class="avatar"/>
        <span id="username">@User.Identity.Name</span>
    }
    <ul class="nav">
        <li class="active"><a asp-controller="App" asp-action="Index">Домой</a></li>
        <li><a asp-controller="App" asp-action="About">О нас</a></li>
        <li><a asp-controller="App" asp-action="Contact">Контакты</a></li>
        @if (User.Identity.IsAuthenticated)
        {
            <li><a asp-controller="App" asp-action="Trips">Мои поездки</a></li>
            <li><a asp-controller="Auth" asp-action="Logout">Выход</a></li>
        }
    </ul>
</div>

<div id="wrapper">
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <ul class="nav navbar-nav navbar-left">
                <li>
                    <button id="sidebarToggle" class="btn btn-primary">
                        <i class="fa fa-angle-left"></i>
                    </button>
                </li>
            </ul>
            <a asp-controller="App" asp-action="Index" class="navbar-brand">Pawelby</a>
        </div>
    </nav>
    <div id="main" class="container-fluid">
        
        <div>
            @RenderBody()
        </div>


    </div>

    <div id="footer" class="container-fluid">
        <div class="navbar navbar-inverse navbar-fixed-bottom">
            <h4 class="text-center text-info">
                &copy; 2015 Pawelby
            </h4>    
        </div>
        

    </div>
</div>

    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <environment names="Development">
        <script type="text/javascript" src="~/js/site.js"></script>
    </environment>
    <environment names="Production, Staging">
        <script type="text/javascript" src="~/lib/_app/site.js"></script>
    </environment>
    
    
    @RenderSection("Scripts", false)

</body>

</html>